import {
  FaStore,
  FaBookOpen,
  FaSpa,
  FaGift,
  FaLayerGroup,
  FaTshirt,
  FaCookieBite,
  FaPaintBrush,
  FaCoffee,
  FaUtensils,
  FaWineGlassAlt,
  FaCouch,
  FaPumpSoap,
  FaSprayCan,
  FaLeaf,
  FaRing,
  FaPrint,
  FaIceCream,
  FaBullhorn,
  FaDumbbell,
  FaPuzzlePiece,
  FaSeedling,
  FaCalendarAlt,
  FaDrumstickBite,
  FaHeartbeat,
  FaPaw,
  FaLaptop,
  FaPizzaSlice,
  FaCar,
  FaGamepad,
  FaServer,
  FaHamburger,
  FaCamera,
  FaFish,
  FaBreadSlice,
  FaGraduationCap,
  FaWineBottle,
  FaGlasses,
  FaBriefcase,
  FaWrench,
  FaCut,
  FaUserAlt,
  FaMobileAlt,
} from "react-icons/fa";
import type { IconType } from "react-icons";

export type Categoria = {
  name: string;
  icon: IconType;
  image: string;
  color: string;
};

export const categorias: Categoria[] = [
  {
    name: "Tienda",
    icon: FaStore,
    image: "/images/categorias/tienda.webp",
    color: "#3b82f6",
  },
  {
    name: "Gestoría",
    icon: FaBookOpen,
    image: "/images/categorias/gestor.webp",
    color: "#64748b",
  },
  {
    name: "Belleza",
    icon: FaSpa,
    image: "/images/categorias/belleza.webp",
    color: "#ec4899",
  },
  {
    name: "Regalos",
    icon: FaGift,
    image: "/images/categorias/regalos.webp",
    color: "#f97316",
  },
  {
    name: "Combos de Comida",
    icon: FaLayerGroup,
    image: "/images/categorias/combos.webp",
    color: "#f59e0b",
  },
  {
    name: "Ropa",
    icon: FaTshirt,
    image: "/images/categorias/ropa.webp",
    color: "#8b5cf6",
  },
  {
    name: "Dulcería",
    icon: FaCookieBite,
    image: "/images/categorias/dulceria.webp",
    color: "#f472b6",
  },
  {
    name: "Artesanías",
    icon: FaPaintBrush,
    image: "/images/categorias/artesania.webp",
    color: "#d97706",
  },
  {
    name: "Cafetería",
    icon: FaCoffee,
    image: "/images/categorias/cafeteria.webp",
    color: "#92400e",
  },
  {
    name: "Restaurante",
    icon: FaUtensils,
    image: "/images/categorias/restaurante.webp",
    color: "#ef4444",
  },
  {
    name: "Bar",
    icon: FaWineGlassAlt,
    image: "/images/categorias/bar.webp",
    color: "#7c3aed",
  },
  {
    name: "Hogar",
    icon: FaCouch,
    image: "/images/categorias/hogar.webp",
    color: "#14b8a6",
  },
  {
    name: "Limpieza",
    icon: FaPumpSoap,
    image: "/images/categorias/aseo.webp",
    color: "#06b6d4",
  },
  {
    name: "Perfumería",
    icon: FaSprayCan,
    image: "/images/categorias/perfumeria.webp",
    color: "#a78bfa",
  },
  {
    name: "Cosmética",
    icon: FaLeaf,
    image: "/images/categorias/Cosmetica.webp",
    color: "#22c55e",
  },
  {
    name: "Joyería",
    icon: FaRing,
    image: "/images/categorias/joyeria.webp",
    color: "#eab308",
  },
  {
    name: "Imprenta",
    icon: FaPrint,
    image: "/images/categorias/imprenta.webp",
    color: "#374151",
  },
  {
    name: "Heladería",
    icon: FaIceCream,
    image: "/images/categorias/heladeria.webp",
    color: "#38bdf8",
  },
  {
    name: "Marketing",
    icon: FaBullhorn,
    image: "/images/categorias/marketing.webp",
    color: "#dc2626",
  },
  {
    name: "Gym",
    icon: FaDumbbell,
    image: "/images/categorias/gym.webp",
    color: "#b91c1c",
  },
  {
    name: "Juguetería",
    icon: FaPuzzlePiece,
    image: "/images/categorias/jugueteria.webp",
    color: "#facc15",
  },
  {
    name: "Orgánicos",
    icon: FaSeedling,
    image: "/images/categorias/naturales.webp",
    color: "#16a34a",
  },
  {
    name: "Eventos",
    icon: FaCalendarAlt,
    image: "/images/categorias/eventos.webp",
    color: "#d946ef",
  },
  {
    name: "Carnicería",
    icon: FaDrumstickBite,
    image: "/images/categorias/carniceria.webp",
    color: "#e11d48",
  },
  {
    name: "Salud",
    icon: FaHeartbeat,
    image: "/images/categorias/salud.webp",
    color: "#f43f5e",
  },
  {
    name: "Mascotas",
    icon: FaPaw,
    image: "/images/categorias/mascotas.webp",
    color: "#fb923c",
  },
  {
    name: "Computadoras",
    icon: FaLaptop,
    image: "/images/categorias/computadoras.webp",
    color: "#2563eb",
  },
  {
    name: "Pizzería",
    icon: FaPizzaSlice,
    image: "/images/categorias/pizzeria.webp",
    color: "#ea580c",
  },
  {
    name: "Automotriz",
    icon: FaCar,
    image: "/images/categorias/automotriz.webp",
    color: "#4b5563",
  },
  {
    name: "Videojuegos",
    icon: FaGamepad,
    image: "/images/categorias/videojuegos.webp",
    color: "#7c3aed",
  },
  {
    name: "Software",
    icon: FaServer,
    image: "/images/categorias/informatica.webp",
    color: "#0ea5e9",
  },
  {
    name: "Floristería",
    icon: FaSeedling,
    image: "/images/categorias/floristeria.webp",
    color: "#a3e635",
  },
  {
    name: "Fotografía",
    icon: FaCamera,
    image: "/images/categorias/fotografia.webp",
    color: "#1f2937",
  },
  {
    name: "Pescadería",
    icon: FaFish,
    image: "/images/categorias/pescaderia.webp",
    color: "#0891b2",
  },
  {
    name: "Panadería",
    icon: FaBreadSlice,
    image: "/images/categorias/panaderia.webp",
    color: "#ca8a04",
  },
  {
    name: "Academia",
    icon: FaGraduationCap,
    image: "/images/categorias/academia.webp",
    color: "#1e3a5f",
  },
  {
    name: "Enoteca",
    icon: FaWineBottle,
    image: "/images/categorias/enoteca.webp",
    color: "#9f1239",
  },
  {
    name: "Óptica",
    icon: FaGlasses,
    image: "/images/categorias/optica.webp",
    color: "#0d9488",
  },
  {
    name: "Consultoría",
    icon: FaBriefcase,
    image: "/images/categorias/consultoria.webp",
    color: "#1e40af",
  },
  {
    name: "Mecánica",
    icon: FaWrench,
    image: "/images/categorias/taller.webp",
    color: "#6b7280",
  },
  {
    name: "Educación",
    icon: FaGraduationCap,
    image: "/images/categorias/educacion.webp",
    color: "#2563eb",
  },
  {
    name: "Barbería",
    icon: FaCut,
    image: "/images/categorias/barberia.webp",
    color: "#991b1b",
  },
  {
    name: "Peluquería",
    icon: FaUserAlt,
    image: "/images/categorias/peluqueria.webp",
    color: "#db2777",
  },
  {
    name: "Comida Rápida",
    icon: FaUtensils,
    image: "/images/categorias/comida-rapida.webp",
    color: "#f59e0b",
  },
  {
    name: "Reparación de Móviles",
    icon: FaMobileAlt,
    image: "/images/categorias/reparacion-de-celulares.webp",
    color: "#10b981",
  },
];
