export const Province = [
  {
    name: "Pinar del Río",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Consolación del Sur", image: "/ejemplo.png" },
      { name: "Guane", image: "/ejemplo.png" },
      { name: "La Palma", image: "/ejemplo.png" },
      { name: "Los Palacios", image: "/ejemplo.png" },
      { name: "Mantua", image: "/ejemplo.png" },
      { name: "Minas de Matahambre", image: "/ejemplo.png" },
      { name: "Pinar del Río", image: "/ejemplo.png" },
      { name: "San Juan y Martínez", image: "/ejemplo.png" },
      { name: "San Luis", image: "/ejemplo.png" },
      { name: "Sandino", image: "/ejemplo.png" },
      { name: "Viñales", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Artemisa",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Alquízar", image: "/ejemplo.png" },
      { name: "Artemisa", image: "/ejemplo.png" },
      { name: "Bauta", image: "/ejemplo.png" },
      { name: "Caimito", image: "/ejemplo.png" },
      { name: "Guanajay", image: "/ejemplo.png" },
      { name: "Güira de Melena", image: "/ejemplo.png" },
      { name: "Mariel", image: "/ejemplo.png" },
      { name: "San Antonio de los Baños", image: "/ejemplo.png" },
      { name: "Bahía Honda", image: "/ejemplo.png" },
      { name: "San Cristóbal", image: "/ejemplo.png" },
      { name: "Candelaria", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Mayabeque",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Batabanó", image: "/ejemplo.png" },
      { name: "Bejucal", image: "/ejemplo.png" },
      { name: "Güines", image: "/ejemplo.png" },
      { name: "Jaruco", image: "/ejemplo.png" },
      { name: "Madruga", image: "/ejemplo.png" },
      { name: "Melena del Sur", image: "/ejemplo.png" },
      { name: "Nueva Paz", image: "/ejemplo.png" },
      { name: "Quivicán", image: "/ejemplo.png" },
      { name: "San José de las Lajas", image: "/ejemplo.png" },
      { name: "San Nicolás de Bari", image: "/ejemplo.png" },
      { name: "Santa Cruz del Norte", image: "/ejemplo.png" },
    ],
  },
  {
    name: "La Habana",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Arroyo Naranjo", image: "/ejemplo.png" },
      { name: "Boyeros", image: "/ejemplo.png" },
      { name: "Centro Habana", image: "/ejemplo.png" },
      { name: "Cerro", image: "/ejemplo.png" },
      { name: "Cotorro", image: "/ejemplo.png" },
      { name: "Diez de Octubre", image: "/ejemplo.png" },
      { name: "Guanabacoa", image: "/ejemplo.png" },
      { name: "Habana del Este", image: "/ejemplo.png" },
      { name: "Habana Vieja", image: "/ejemplo.png" },
      { name: "La Lisa", image: "/ejemplo.png" },
      { name: "Marianao", image: "/ejemplo.png" },
      { name: "Playa", image: "/ejemplo.png" },
      { name: "Plaza de la Revolución", image: "/ejemplo.png" },
      { name: "Regla", image: "/ejemplo.png" },
      { name: "San Miguel del Padrón", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Matanzas",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Calimete", image: "/ejemplo.png" },
      { name: "Cárdenas", image: "/ejemplo.png" },
      { name: "Ciénaga de Zapata", image: "/ejemplo.png" },
      { name: "Colón", image: "/ejemplo.png" },
      { name: "Jagüey Grande", image: "/ejemplo.png" },
      { name: "Jovellanos", image: "/ejemplo.png" },
      { name: "Limonar", image: "/ejemplo.png" },
      { name: "Los Arabos", image: "/ejemplo.png" },
      { name: "Martí", image: "/ejemplo.png" },
      { name: "Matanzas", image: "/ejemplo.png" },
      { name: "Pedro Betancourt", image: "/ejemplo.png" },
      { name: "Perico", image: "/ejemplo.png" },
      { name: "Unión de Reyes", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Villa Clara",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Caibarién", image: "/ejemplo.png" },
      { name: "Camajuaní", image: "/ejemplo.png" },
      { name: "Cifuentes", image: "/ejemplo.png" },
      { name: "Corralillo", image: "/ejemplo.png" },
      { name: "Encrucijada", image: "/ejemplo.png" },
      { name: "Manicaragua", image: "/ejemplo.png" },
      { name: "Placetas", image: "/ejemplo.png" },
      { name: "Quemado de Güines", image: "/ejemplo.png" },
      { name: "Ranchuelo", image: "/ejemplo.png" },
      { name: "Remedios", image: "/ejemplo.png" },
      { name: "Sagua la Grande", image: "/ejemplo.png" },
      { name: "Santa Clara", image: "/ejemplo.png" },
      { name: "Santo Domingo", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Cienfuegos",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Abreus", image: "/ejemplo.png" },
      { name: "Aguada de Pasajeros", image: "/ejemplo.png" },
      { name: "Cienfuegos", image: "/ejemplo.png" },
      { name: "Cruces", image: "/ejemplo.png" },
      { name: "Cumanayagua", image: "/ejemplo.png" },
      { name: "Palmira", image: "/ejemplo.png" },
      { name: "Rodas", image: "/ejemplo.png" },
      { name: "Lajas", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Sancti Spíritus",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Cabaiguán", image: "/ejemplo.png" },
      { name: "Fomento", image: "/ejemplo.png" },
      { name: "Jatibonico", image: "/ejemplo.png" },
      { name: "La Sierpe", image: "/ejemplo.png" },
      { name: "Sancti Spíritus", image: "/ejemplo.png" },
      { name: "Taguasco", image: "/ejemplo.png" },
      { name: "Trinidad", image: "/ejemplo.png" },
      { name: "Yaguajay", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Ciego de Ávila",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Ciro Redondo", image: "/ejemplo.png" },
      { name: "Baraguá", image: "/ejemplo.png" },
      { name: "Bolivia", image: "/ejemplo.png" },
      { name: "Chambas", image: "/ejemplo.png" },
      { name: "Ciego de Ávila", image: "/ejemplo.png" },
      { name: "Florencia", image: "/ejemplo.png" },
      { name: "Majagua", image: "/ejemplo.png" },
      { name: "Morón", image: "/ejemplo.png" },
      { name: "Primero de Enero", image: "/ejemplo.png" },
      { name: "Venezuela", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Camagüey",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Camagüey", image: "/ejemplo.png" },
      { name: "Carlos Manuel de Céspedes", image: "/ejemplo.png" },
      { name: "Esmeralda", image: "/ejemplo.png" },
      { name: "Florida", image: "/ejemplo.png" },
      { name: "Guáimaro", image: "/ejemplo.png" },
      { name: "Jimaguayú", image: "/ejemplo.png" },
      { name: "Minas", image: "/ejemplo.png" },
      { name: "Najasa", image: "/ejemplo.png" },
      { name: "Nuevitas", image: "/ejemplo.png" },
      { name: "Santa Cruz del Sur", image: "/ejemplo.png" },
      { name: "Sibanicú", image: "/ejemplo.png" },
      { name: "Sierra de Cubitas", image: "/ejemplo.png" },
      { name: "Vertientes", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Las Tunas",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Amancio", image: "/ejemplo.png" },
      { name: "Colombia", image: "/ejemplo.png" },
      { name: "Jesús Menéndez", image: "/ejemplo.png" },
      { name: "Jobabo", image: "/ejemplo.png" },
      { name: "Las Tunas", image: "/ejemplo.png" },
      { name: "Majibacoa", image: "/ejemplo.png" },
      { name: "Manatí", image: "/ejemplo.png" },
      { name: "Puerto Padre", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Holguín",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Antilla", image: "/ejemplo.png" },
      { name: "Báguanos", image: "/ejemplo.png" },
      { name: "Banes", image: "/ejemplo.png" },
      { name: "Cacocum", image: "/ejemplo.png" },
      { name: "Calixto García", image: "/ejemplo.png" },
      { name: "Cueto", image: "/ejemplo.png" },
      { name: "Frank País", image: "/ejemplo.png" },
      { name: "Gibara", image: "/ejemplo.png" },
      { name: "Holguín", image: "/ejemplo.png" },
      { name: "Mayarí", image: "/ejemplo.png" },
      { name: "Moa", image: "/ejemplo.png" },
      { name: "Rafael Freyre", image: "/ejemplo.png" },
      { name: "Sagua de Tánamo", image: "/ejemplo.png" },
      { name: "Urbano Noris", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Granma",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Bartolomé Masó", image: "/ejemplo.png" },
      { name: "Bayamo", image: "/ejemplo.png" },
      { name: "Buey Arriba", image: "/ejemplo.png" },
      { name: "Campechuela", image: "/ejemplo.png" },
      { name: "Cauto Cristo", image: "/ejemplo.png" },
      { name: "Guisa", image: "/ejemplo.png" },
      { name: "Jiguaní", image: "/ejemplo.png" },
      { name: "Manzanillo", image: "/ejemplo.png" },
      { name: "Media Luna", image: "/ejemplo.png" },
      { name: "Niquero", image: "/ejemplo.png" },
      { name: "Pilón", image: "/ejemplo.png" },
      { name: "Río Cauto", image: "/ejemplo.png" },
      { name: "Yara", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Santiago de Cuba",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Contramaestre", image: "/ejemplo.png" },
      { name: "Guamá", image: "/ejemplo.png" },
      { name: "Julio Antonio Mella", image: "/ejemplo.png" },
      { name: "Palma Soriano", image: "/ejemplo.png" },
      { name: "San Luis", image: "/ejemplo.png" },
      { name: "Santiago de Cuba", image: "/ejemplo.png" },
      { name: "Segundo Frente", image: "/ejemplo.png" },
      { name: "Songo la Maya", image: "/ejemplo.png" },
      { name: "Tercer Frente", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Guantánamo",
    image: "/ejemplo.png",
    municipalities: [
      { name: "Baracoa", image: "/ejemplo.png" },
      { name: "Caimanera", image: "/ejemplo.png" },
      { name: "El Salvador", image: "/ejemplo.png" },
      { name: "Guantánamo", image: "/ejemplo.png" },
      { name: "Imías", image: "/ejemplo.png" },
      { name: "Maisí", image: "/ejemplo.png" },
      { name: "Manuel Tames", image: "/ejemplo.png" },
      { name: "Niceto Pérez", image: "/ejemplo.png" },
      { name: "San Antonio del Sur", image: "/ejemplo.png" },
      { name: "Yateras", image: "/ejemplo.png" },
    ],
  },
  {
    name: "Municipio Especial",
    image: "/ejemplo.png",
    municipalities: [{ name: "Isla de la Juventud", image: "/ejemplo.png" }],
  },
];
