export const Provincias = [
  {
    id: "pinar-del-rio",
    name: "Pinar del Río",
    image: "/ejemplo.png",
    municipalities: [
      {
        id: "consolacion-del-sur",
        name: "Consolación del Sur",
        image: "/ejemplo.png",
      },
      { id: "guane", name: "Guane", image: "/ejemplo.png" },
      { id: "la-palma", name: "La Palma", image: "/ejemplo.png" },
      { id: "los-palacios", name: "Los Palacios", image: "/ejemplo.png" },
      { id: "mantua", name: "Mantua", image: "/ejemplo.png" },
      {
        id: "minas-de-matahambre",
        name: "Minas de Matahambre",
        image: "/ejemplo.png",
      },
      { id: "pinar-del-rio", name: "Pinar del Río", image: "/ejemplo.png" },
      {
        id: "san-juan-y-martinez",
        name: "San Juan y Martínez",
        image: "/ejemplo.png",
      },
      { id: "san-luis", name: "San Luis", image: "/ejemplo.png" },
      { id: "sandino", name: "Sandino", image: "/ejemplo.png" },
      { id: "vinales", name: "Viñales", image: "/ejemplo.png" },
    ],
  },
  {
    id: "artemisa",
    name: "Artemisa",
    image: "/ejemplo.png",
    municipalities: [
      { id: "alquizar", name: "Alquízar", image: "/ejemplo.png" },
      { id: "artemisa", name: "Artemisa", image: "/ejemplo.png" },
      { id: "bauta", name: "Bauta", image: "/ejemplo.png" },
      { id: "caimito", name: "Caimito", image: "/ejemplo.png" },
      { id: "guanajay", name: "Guanajay", image: "/ejemplo.png" },
      { id: "guira-de-melena", name: "Güira de Melena", image: "/ejemplo.png" },
      { id: "mariel", name: "Mariel", image: "/ejemplo.png" },
      {
        id: "san-antonio-de-los-banos",
        name: "San Antonio de los Baños",
        image: "/ejemplo.png",
      },
      { id: "bahia-honda", name: "Bahía Honda", image: "/ejemplo.png" },
      { id: "san-cristobal", name: "San Cristóbal", image: "/ejemplo.png" },
      { id: "candelaria", name: "Candelaria", image: "/ejemplo.png" },
    ],
  },
  {
    id: "mayabeque",
    name: "Mayabeque",
    image: "/ejemplo.png",
    municipalities: [
      { id: "batabano", name: "Batabanó", image: "/ejemplo.png" },
      { id: "bejucal", name: "Bejucal", image: "/ejemplo.png" },
      { id: "guines", name: "Güines", image: "/ejemplo.png" },
      { id: "jaruco", name: "Jaruco", image: "/ejemplo.png" },
      { id: "madruga", name: "Madruga", image: "/ejemplo.png" },
      { id: "melena-del-sur", name: "Melena del Sur", image: "/ejemplo.png" },
      { id: "nueva-paz", name: "Nueva Paz", image: "/ejemplo.png" },
      { id: "quivican", name: "Quivicán", image: "/ejemplo.png" },
      {
        id: "san-jose-de-las-lajas",
        name: "San José de las Lajas",
        image: "/ejemplo.png",
      },
      {
        id: "san-nicolas-de-bari",
        name: "San Nicolás de Bari",
        image: "/ejemplo.png",
      },
      {
        id: "santa-cruz-del-norte",
        name: "Santa Cruz del Norte",
        image: "/ejemplo.png",
      },
    ],
  },
  {
    id: "la-habana",
    name: "La Habana",
    image: "/ejemplo.png",
    municipalities: [
      { id: "arroyo-naranjo", name: "Arroyo Naranjo", image: "/ejemplo.png" },
      { id: "boyeros", name: "Boyeros", image: "/ejemplo.png" },
      { id: "centro-habana", name: "Centro Habana", image: "/ejemplo.png" },
      { id: "cerro", name: "Cerro", image: "/ejemplo.png" },
      { id: "cotorro", name: "Cotorro", image: "/ejemplo.png" },
      { id: "diez-de-octubre", name: "Diez de Octubre", image: "/ejemplo.png" },
      { id: "guanabacoa", name: "Guanabacoa", image: "/ejemplo.png" },
      { id: "habana-del-este", name: "Habana del Este", image: "/ejemplo.png" },
      { id: "habana-vieja", name: "Habana Vieja", image: "/ejemplo.png" },
      { id: "la-lisa", name: "La Lisa", image: "/ejemplo.png" },
      { id: "marianao", name: "Marianao", image: "/ejemplo.png" },
      { id: "playa", name: "Playa", image: "/ejemplo.png" },
      {
        id: "plaza-de-la-revolucion",
        name: "Plaza de la Revolución",
        image: "/ejemplo.png",
      },
      { id: "regla", name: "Regla", image: "/ejemplo.png" },
      {
        id: "san-miguel-del-padron",
        name: "San Miguel del Padrón",
        image: "/ejemplo.png",
      },
    ],
  },
  {
    id: "matanzas",
    name: "Matanzas",
    image: "/ejemplo.png",
    municipalities: [
      { id: "calimete", name: "Calimete", image: "/ejemplo.png" },
      { id: "cardenas", name: "Cárdenas", image: "/ejemplo.png" },
      {
        id: "cienaga-de-zapata",
        name: "Ciénaga de Zapata",
        image: "/ejemplo.png",
      },
      { id: "colon", name: "Colón", image: "/ejemplo.png" },
      { id: "jaguey-grande", name: "Jagüey Grande", image: "/ejemplo.png" },
      { id: "jovellanos", name: "Jovellanos", image: "/ejemplo.png" },
      { id: "limonar", name: "Limonar", image: "/ejemplo.png" },
      { id: "los-arabos", name: "Los Arabos", image: "/ejemplo.png" },
      { id: "marti", name: "Martí", image: "/ejemplo.png" },
      { id: "matanzas", name: "Matanzas", image: "/ejemplo.png" },
      {
        id: "pedro-betancourt",
        name: "Pedro Betancourt",
        image: "/ejemplo.png",
      },
      { id: "perico", name: "Perico", image: "/ejemplo.png" },
      { id: "union-de-reyes", name: "Unión de Reyes", image: "/ejemplo.png" },
    ],
  },
  {
    id: "villa-clara",
    name: "Villa Clara",
    image: "/ejemplo.png",
    municipalities: [
      { id: "caibarien", name: "Caibarién", image: "/ejemplo.png" },
      { id: "camajuani", name: "Camajuaní", image: "/ejemplo.png" },
      { id: "cifuentes", name: "Cifuentes", image: "/ejemplo.png" },
      { id: "corralillo", name: "Corralillo", image: "/ejemplo.png" },
      { id: "encrucijada", name: "Encrucijada", image: "/ejemplo.png" },
      { id: "manicaragua", name: "Manicaragua", image: "/ejemplo.png" },
      { id: "placetas", name: "Placetas", image: "/ejemplo.png" },
      {
        id: "quemado-de-guines",
        name: "Quemado de Güines",
        image: "/ejemplo.png",
      },
      { id: "ranchuelo", name: "Ranchuelo", image: "/ejemplo.png" },
      { id: "remedios", name: "Remedios", image: "/ejemplo.png" },
      { id: "sagua-la-grande", name: "Sagua la Grande", image: "/ejemplo.png" },
      { id: "santa-clara", name: "Santa Clara", image: "/ejemplo.png" },
      { id: "santo-domingo", name: "Santo Domingo", image: "/ejemplo.png" },
    ],
  },
  {
    id: "cienfuegos",
    name: "Cienfuegos",
    image: "/ejemplo.png",
    municipalities: [
      { id: "abreus", name: "Abreus", image: "/ejemplo.png" },
      {
        id: "aguada-de-pasajeros",
        name: "Aguada de Pasajeros",
        image: "/ejemplo.png",
      },
      { id: "cienfuegos", name: "Cienfuegos", image: "/ejemplo.png" },
      { id: "cruces", name: "Cruces", image: "/ejemplo.png" },
      { id: "cumanayagua", name: "Cumanayagua", image: "/ejemplo.png" },
      { id: "palmira", name: "Palmira", image: "/ejemplo.png" },
      { id: "rodas", name: "Rodas", image: "/ejemplo.png" },
      { id: "lajas", name: "Lajas", image: "/ejemplo.png" },
    ],
  },
  {
    id: "sancti-spiritus",
    name: "Sancti Spíritus",
    image: "/ejemplo.png",
    municipalities: [
      { id: "cabaiguan", name: "Cabaiguán", image: "/ejemplo.png" },
      { id: "fomento", name: "Fomento", image: "/ejemplo.png" },
      { id: "jatibonico", name: "Jatibonico", image: "/ejemplo.png" },
      { id: "la-sierpe", name: "La Sierpe", image: "/ejemplo.png" },
      { id: "sancti-spiritus", name: "Sancti Spíritus", image: "/ejemplo.png" },
      { id: "taguasco", name: "Taguasco", image: "/ejemplo.png" },
      { id: "trinidad", name: "Trinidad", image: "/ejemplo.png" },
      { id: "yaguajay", name: "Yaguajay", image: "/ejemplo.png" },
    ],
  },
  {
    id: "ciego-de-avila",
    name: "Ciego de Ávila",
    image: "/ejemplo.png",
    municipalities: [
      { id: "ciro-redondo", name: "Ciro Redondo", image: "/ejemplo.png" },
      { id: "baragua", name: "Baraguá", image: "/ejemplo.png" },
      { id: "bolivia", name: "Bolivia", image: "/ejemplo.png" },
      { id: "chambas", name: "Chambas", image: "/ejemplo.png" },
      { id: "ciego-de-avila", name: "Ciego de Ávila", image: "/ejemplo.png" },
      { id: "florencia", name: "Florencia", image: "/ejemplo.png" },
      { id: "majagua", name: "Majagua", image: "/ejemplo.png" },
      { id: "moron", name: "Morón", image: "/ejemplo.png" },
      {
        id: "primero-de-enero",
        name: "Primero de Enero",
        image: "/ejemplo.png",
      },
      { id: "venezuela", name: "Venezuela", image: "/ejemplo.png" },
    ],
  },
  {
    id: "camaguey",
    name: "Camagüey",
    image: "/ejemplo.png",
    municipalities: [
      { id: "camaguey", name: "Camagüey", image: "/ejemplo.png" },
      {
        id: "carlos-manuel-de-cespedes",
        name: "Carlos Manuel de Céspedes",
        image: "/ejemplo.png",
      },
      { id: "esmeralda", name: "Esmeralda", image: "/ejemplo.png" },
      { id: "florida", name: "Florida", image: "/ejemplo.png" },
      { id: "guaimaro", name: "Guáimaro", image: "/ejemplo.png" },
      { id: "jimaguayu", name: "Jimaguayú", image: "/ejemplo.png" },
      { id: "minas", name: "Minas", image: "/ejemplo.png" },
      { id: "najasa", name: "Najasa", image: "/ejemplo.png" },
      { id: "nuevitas", name: "Nuevitas", image: "/ejemplo.png" },
      {
        id: "santa-cruz-del-sur",
        name: "Santa Cruz del Sur",
        image: "/ejemplo.png",
      },
      { id: "sibanico", name: "Sibanicú", image: "/ejemplo.png" },
      {
        id: "sierra-de-cubitas",
        name: "Sierra de Cubitas",
        image: "/ejemplo.png",
      },
      { id: "vertientes", name: "Vertientes", image: "/ejemplo.png" },
    ],
  },
  {
    id: "las-tunas",
    name: "Las Tunas",
    image: "/ejemplo.png",
    municipalities: [
      { id: "amancio", name: "Amancio", image: "/ejemplo.png" },
      { id: "colombia", name: "Colombia", image: "/ejemplo.png" },
      { id: "jesus-menendez", name: "Jesús Menéndez", image: "/ejemplo.png" },
      { id: "jobabo", name: "Jobabo", image: "/ejemplo.png" },
      { id: "las-tunas", name: "Las Tunas", image: "/ejemplo.png" },
      { id: "majibacoa", name: "Majibacoa", image: "/ejemplo.png" },
      { id: "manati", name: "Manatí", image: "/ejemplo.png" },
      { id: "puerto-padre", name: "Puerto Padre", image: "/ejemplo.png" },
    ],
  },
  {
    id: "holguin",
    name: "Holguín",
    image: "/ejemplo.png",
    municipalities: [
      { id: "antilla", name: "Antilla", image: "/ejemplo.png" },
      { id: "baguanos", name: "Báguanos", image: "/ejemplo.png" },
      { id: "banes", name: "Banes", image: "/ejemplo.png" },
      { id: "cacocum", name: "Cacocum", image: "/ejemplo.png" },
      { id: "calixto-garcia", name: "Calixto García", image: "/ejemplo.png" },
      { id: "cueto", name: "Cueto", image: "/ejemplo.png" },
      { id: "frank-pais", name: "Frank País", image: "/ejemplo.png" },
      { id: "gibara", name: "Gibara", image: "/ejemplo.png" },
      { id: "holguin", name: "Holguín", image: "/ejemplo.png" },
      { id: "mayari", name: "Mayarí", image: "/ejemplo.png" },
      { id: "moa", name: "Moa", image: "/ejemplo.png" },
      { id: "rafael-freyre", name: "Rafael Freyre", image: "/ejemplo.png" },
      { id: "sagua-de-tanamo", name: "Sagua de Tánamo", image: "/ejemplo.png" },
      { id: "urbano-noris", name: "Urbano Noris", image: "/ejemplo.png" },
    ],
  },
  {
    id: "granma",
    name: "Granma",
    image: "/ejemplo.png",
    municipalities: [
      { id: "bartolome-maso", name: "Bartolomé Masó", image: "/ejemplo.png" },
      { id: "bayamo", name: "Bayamo", image: "/ejemplo.png" },
      { id: "buey-arriba", name: "Buey Arriba", image: "/ejemplo.png" },
      { id: "campechuela", name: "Campechuela", image: "/ejemplo.png" },
      { id: "cauto-cristo", name: "Cauto Cristo", image: "/ejemplo.png" },
      { id: "guisa", name: "Guisa", image: "/ejemplo.png" },
      { id: "jiguani", name: "Jiguaní", image: "/ejemplo.png" },
      { id: "manzanillo", name: "Manzanillo", image: "/ejemplo.png" },
      { id: "media-luna", name: "Media Luna", image: "/ejemplo.png" },
      { id: "niquero", name: "Niquero", image: "/ejemplo.png" },
      { id: "pilon", name: "Pilón", image: "/ejemplo.png" },
      { id: "rio-cauto", name: "Río Cauto", image: "/ejemplo.png" },
      { id: "yara", name: "Yara", image: "/ejemplo.png" },
    ],
  },
  {
    id: "santiago-de-cuba",
    name: "Santiago de Cuba",
    image: "/ejemplo.png",
    municipalities: [
      { id: "contramaestre", name: "Contramaestre", image: "/ejemplo.png" },
      { id: "guama", name: "Guamá", image: "/ejemplo.png" },
      {
        id: "julio-antonio-mella",
        name: "Julio Antonio Mella",
        image: "/ejemplo.png",
      },
      { id: "palma-soriano", name: "Palma Soriano", image: "/ejemplo.png" },
      { id: "san-luis", name: "San Luis", image: "/ejemplo.png" },
      {
        id: "santiago-de-cuba",
        name: "Santiago de Cuba",
        image: "/ejemplo.png",
      },
      { id: "segundo-frente", name: "Segundo Frente", image: "/ejemplo.png" },
      { id: "songo-la-maya", name: "Songo la Maya", image: "/ejemplo.png" },
      { id: "tercer-frente", name: "Tercer Frente", image: "/ejemplo.png" },
    ],
  },
  {
    id: "guantanamo",
    name: "Guantánamo",
    image: "/ejemplo.png",
    municipalities: [
      { id: "baracoa", name: "Baracoa", image: "/ejemplo.png" },
      { id: "caimanera", name: "Caimanera", image: "/ejemplo.png" },
      { id: "el-salvador", name: "El Salvador", image: "/ejemplo.png" },
      { id: "guantanamo", name: "Guantánamo", image: "/ejemplo.png" },
      { id: "imias", name: "Imías", image: "/ejemplo.png" },
      { id: "maisi", name: "Maisí", image: "/ejemplo.png" },
      { id: "manuel-tames", name: "Manuel Tames", image: "/ejemplo.png" },
      { id: "niceto-perez", name: "Niceto Pérez", image: "/ejemplo.png" },
      {
        id: "san-antonio-del-sur",
        name: "San Antonio del Sur",
        image: "/ejemplo.png",
      },
      { id: "yateras", name: "Yateras", image: "/ejemplo.png" },
    ],
  },
  {
    id: "municipio-especial",
    name: "Municipio Especial",
    image: "/ejemplo.png",
    municipalities: [
      {
        id: "isla-de-la-juventud",
        name: "Isla de la Juventud",
        image: "/ejemplo.png",
      },
    ],
  },
];
